# Generated by Django 6.0 on 2026-01-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchats',
            name='session',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
